# Generated by Django 3.1.2 on 2021-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='user_images/default.jpg', upload_to='user_images/%Y/%m/%d'),
        ),
    ]
