# Generated by Django 3.1.2 on 2021-07-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20210709_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
    ]
