# Generated by Django 3.1.2 on 2021-08-05 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_auto_20210802_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='memo.goal'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='memo.goal'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.lesson'),
        ),
        migrations.AlterField(
            model_name='section',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memo.goal'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=200)),
                ('goal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='memo.goal')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memo.section')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.theme', verbose_name='Цель'),
        ),
    ]
