# Generated by Django 3.1.2 on 2021-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_auto_20210805_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
