# Generated by Django 3.1.2 on 2021-08-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_lesson_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='is_active',
            new_name='active_lesson',
        ),
    ]
