# Generated by Django 3.1.2 on 2021-08-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0007_auto_20210805_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='last_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='memo.section'),
        ),
    ]
