# Generated by Django 3.1.2 on 2021-08-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0010_auto_20210812_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='active_lesson',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='last_used',
        ),
        migrations.AlterField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='memo.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='memo.goal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='memo.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.goal', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memo.theme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='section',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memo.goal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='memo.goal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='memo.section', verbose_name='Section'),
        ),
    ]
