# Generated by Django 3.1.2 on 2021-08-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0012_theme_last_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='last_used',
        ),
    ]
